export enum TagDataEnum {
    pubCategory = 0,
    pubType = 1,
    pubTitle = 2,
    pubSource = 3,
    pubThemeTag = 4,
    pubContent = 5,
    pubAbstract = 6,
    pubData = 7,
    pubPrimaryLink = 8,
    pubLink = 9,
    authorName = 10,
    namesOfAuthors = 11,
    authorAffiliation = 12,
    affiliationOfAuthors = 13,
}